#
# 名前: 回数
# 孕むまでの必要回数
#
kakikama: 50
rosec_pin: 100
urn1o: 100
YOSHIKO__chan__: 30000
23zi_51hun: 75
suzuki2929: 120
kikaru0014: 100
dbk_huuka: 150
ikeko_99: 100
kono_a: 50
_hinana_: 75
tabi_meido: 100
fakevox24: 100
Nishito_31: 25
imo64: 25
tan_sio: 25

users:
  - kakikama
  - rosec_pin
  - urn1o
  - YOSHIKO__chan__
  - 23zi_51hun
  - suzuki2929
  - kikaru0014
  - dbk_huuka
  - ikeko_99
  - kono_a
  - _hinana_
  - tabi_meido
  - fakevox24
  - Nishito_31
  - imo64
  - tan_sio

settings:
#
# 生まれてこないエンティティ
# EntityType.XXXのXXXの部分を記入
# 内部実装がEntityType.values().clone()のため
#
  entities:
    - ENDER_DRAGON
    - DRAGON_FIREBALL
    - ENDER_CRYSTAL

#
# 性病にかかる確率
# X分の1の確率でかかる
# 100の場合=1% (エンティティが生まれる処理の際に抽選)
#
  probability:
    # クラミジア
    chlamydia: 100
    # 淋病
    gonorrhea: 100
    # 梅毒
    syphilis: 100
    # ヘルペス
    herpes: 100

#
# 性病の効果が現れる確率
# X分の1の確率でかかる
# 100の場合=1% (0.1秒毎に抽選)
#
  run:
    # クラミジア
    chlamydia: 100
    # 淋病
    gonorrhea: 100
    # 梅毒
    syphilis: 100
    # ヘルペス
    herpes: 100

#
# 性病の効果を表すパーティクル
# コンソールからコマンドを実行する
# 毎tick実行
# %player% < 対象プレイヤー
#
  effect:
    # クラミジア
    chlamydia:
      - "execute at %player% run particle minecraft:falling_obsidian_tear ~ ~0.7 ~ 0.1 0 0.1 0.01 10 force"
    # 淋病
    gonorrhea:
      - "execute at %player% run particle minecraft:emote_salt ~ ~0.7 ~ 0.1 0 0.1 0.01 10 force"
    # 梅毒
    syphilis:
      - "execute at %player% run particle minecraft:item_slime ~ ~0.7 ~ 0 0 0 0.001 10 force"
    # ヘルペス
    herpes:
      - "execute at %player% run particle minecraft:dripping_honey ~ ~0.6 ~ 0.1 0.1 0.1 0.01 10 force"