settings:
#
# 性病にかかる確率
# X分の1の確率でかかる
# 100の場合=1% (ToggleSneakEventが発火する処理の際に抽選)
#
  probability:
    # クラミジア
    chlamydia: 1000
    # 淋病
    gonorrhea: 1000
    # 梅毒
    syphilis: 1000
    # ヘルペス
    herpes: 1000

#
# 性病の効果が現れる確率
# X分の1の確率でかかる
# 100の場合=1% (0.1秒毎に抽選)
#
  run:
    # クラミジア
    chlamydia: 100
    # 淋病
    gonorrhea: 100
    # 梅毒
    syphilis: 100
    # ヘルペス
    herpes: 100