settings:
#
# 性病にかかる確率
# X分の1の確率でかかる
# 100の場合=1% (ToggleSneakEventが発火する処理の際に抽選)
#
  probability:
    # クラミジア
    chlamydia: 100
    # 淋病
    gonorrhea: 100
    # 梅毒
    syphilis: 100
    # ヘルペス
    herpes: 100

#
# 性病の効果が現れる確率
# X分の1の確率でかかる
# 100の場合=1% (0.1秒毎に抽選)
#
  run:
    # クラミジア
    chlamydia: 100
    # 淋病
    gonorrhea: 100
    # 梅毒
    syphilis: 100
    # ヘルペス
    herpes: 100

#
# パーティクルの数
# 1tick毎、1度に表示するパーティクルの数
# 初期値:5
#
  particle:
    # クラミジア
    chlamydia: 5
    # 淋病
    gonorrhea: 5
    # 梅毒
    syphilis: 5
    # ヘルペス
    herpes: 5
